#ifndef PROFILE_H
#define PROFILE_H

#include "vm.h"

typedef struct {
    double execution_time_ms;
    uint32_t cache_hits;
    uint32_t cache_misses;
    uint32_t evictions;
    uint32_t page_accesses;
    ExecuteResult plan_result;
    ExecuteResult execute_result;
} QueryProfile;

/*
 * Execute a SELECT through the normal planner/VM path while measuring the
 * buffer-pool deltas generated by the actual execution. The function prints
 * the same query plan used by EXPLAIN followed by the real query result.
 *
 * Returns false when statement/profile/table is NULL or the statement is not
 * a SELECT. In that case no statement is executed.
 */
bool query_profile_execute(Statement* statement, Table* table, QueryProfile* profile);

#endif /* PROFILE_H */
